package form;

import java.awt.Dimension;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import perpustakaan.menuLogin;

/**
 *
 * @author oyeaaa
 */
public class formUtamaAdmin extends javax.swing.JFrame {

    /**
     * Creates new form formUtamaAdmin
     */
    public formUtamaAdmin() {
        initComponents();
        
        // Menset ukuran layar utama ke full size
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        
        lblGreet.setText("SELAMAT DATANG " + formLoginAdmin.getNama().toUpperCase());
          
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelUtama = new javax.swing.JDesktopPane();
        lblGreet = new javax.swing.JLabel();
        btnKelolaBuku = new javax.swing.JButton();
        btnKelolaAnggota = new javax.swing.JButton();
        btnKelolaPeminjaman = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        menuBar = new javax.swing.JMenuBar();
        menuAkun = new javax.swing.JMenu();
        menuLogout = new javax.swing.JMenuItem();
        menuData = new javax.swing.JMenu();
        formKelolaBuku = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        formKelolaAnggota = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        formKelolaPeminjaman = new javax.swing.JMenuItem();
        menuTentangKita = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MENU UTAMA ADMIN");

        panelUtama.setPreferredSize(new java.awt.Dimension(1366, 632));

        lblGreet.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        lblGreet.setForeground(new java.awt.Color(255, 255, 255));
        lblGreet.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblGreet.setPreferredSize(new java.awt.Dimension(1366, 0));

        btnKelolaBuku.setBackground(new java.awt.Color(75, 75, 75));
        btnKelolaBuku.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        btnKelolaBuku.setForeground(new java.awt.Color(255, 255, 255));
        btnKelolaBuku.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/buku.png"))); // NOI18N
        btnKelolaBuku.setText("Pengelolaan Data Buku");
        btnKelolaBuku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKelolaBukuActionPerformed(evt);
            }
        });

        btnKelolaAnggota.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        btnKelolaAnggota.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/anggota.png"))); // NOI18N
        btnKelolaAnggota.setText("Pengelolaan Data Anggota");
        btnKelolaAnggota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKelolaAnggotaActionPerformed(evt);
            }
        });

        btnKelolaPeminjaman.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        btnKelolaPeminjaman.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/histori.png"))); // NOI18N
        btnKelolaPeminjaman.setText("Pengelolaan Data Peminjaman");
        btnKelolaPeminjaman.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKelolaPeminjamanActionPerformed(evt);
            }
        });

        btnLogout.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        btnLogout.setText("LOGOUT");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        panelUtama.setLayer(lblGreet, javax.swing.JLayeredPane.DEFAULT_LAYER);
        panelUtama.setLayer(btnKelolaBuku, javax.swing.JLayeredPane.DEFAULT_LAYER);
        panelUtama.setLayer(btnKelolaAnggota, javax.swing.JLayeredPane.DEFAULT_LAYER);
        panelUtama.setLayer(btnKelolaPeminjaman, javax.swing.JLayeredPane.DEFAULT_LAYER);
        panelUtama.setLayer(btnLogout, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout panelUtamaLayout = new javax.swing.GroupLayout(panelUtama);
        panelUtama.setLayout(panelUtamaLayout);
        panelUtamaLayout.setHorizontalGroup(
            panelUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelUtamaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblGreet, javax.swing.GroupLayout.PREFERRED_SIZE, 1366, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelUtamaLayout.createSequentialGroup()
                        .addGap(301, 301, 301)
                        .addGroup(panelUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnKelolaBuku, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnKelolaPeminjaman, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(93, 93, 93)
                        .addGroup(panelUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnKelolaAnggota, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)))))
        );
        panelUtamaLayout.setVerticalGroup(
            panelUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelUtamaLayout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(lblGreet, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(77, 77, 77)
                .addGroup(panelUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnKelolaBuku, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnKelolaAnggota, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(panelUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnKelolaPeminjaman, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(130, Short.MAX_VALUE))
        );

        menuAkun.setText("Akun");

        menuLogout.setText("Logout");
        menuLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuLogoutActionPerformed(evt);
            }
        });
        menuAkun.add(menuLogout);

        menuBar.add(menuAkun);

        menuData.setText("Data");

        formKelolaBuku.setText("Data Buku");
        formKelolaBuku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                formKelolaBukuActionPerformed(evt);
            }
        });
        menuData.add(formKelolaBuku);
        menuData.add(jSeparator1);

        formKelolaAnggota.setText("Data Anggota");
        formKelolaAnggota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                formKelolaAnggotaActionPerformed(evt);
            }
        });
        menuData.add(formKelolaAnggota);
        menuData.add(jSeparator2);

        formKelolaPeminjaman.setText("Data Peminjaman");
        formKelolaPeminjaman.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                formKelolaPeminjamanActionPerformed(evt);
            }
        });
        menuData.add(formKelolaPeminjaman);

        menuBar.add(menuData);

        menuTentangKita.setText("Tentang Kami");
        menuTentangKita.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuTentangKitaMouseClicked(evt);
            }
        });
        menuBar.add(menuTentangKita);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelUtama, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelUtama, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuLogoutActionPerformed
        // Instance menu login
        menuLogin menuLogin = new menuLogin();
        
        // Tampilkan menu login utama
        menuLogin.setVisible(true);
        
        // Hapus tampilan form utama admin
        this.dispose();
        
        // Tampilkan pesan berhasil
        JOptionPane.showMessageDialog(null, "Anda berhasil logout");
    }//GEN-LAST:event_menuLogoutActionPerformed

    private void formKelolaBukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_formKelolaBukuActionPerformed
        // Menghapus komponen lain di panel utama
        panelUtama.removeAll();
        panelUtama.repaint();
        
        // Instance class form kelola buku
        formKelolaBuku kelolaBuku = new formKelolaBuku();
        
        // Mengambil ukuran layar utama dan layar form kelola buku
        Dimension layarUtama = this.getSize();
        Dimension layarKelolaBuku = kelolaBuku.getSize();
        
        // Set posisi form kelola buku ke center
        kelolaBuku.setLocation((layarUtama.width - layarKelolaBuku.width)/2, (layarUtama.height - layarKelolaBuku.height)/4);
        
        // Menambahkan halaman form kelola buku di panel utama
        panelUtama.add(kelolaBuku);
        kelolaBuku.setVisible(true);
        
        // Menambahkan kembali komponen yang ada di panel utama
        panelUtama.add(lblGreet);
        panelUtama.add(btnKelolaBuku);
        panelUtama.add(btnKelolaAnggota);
        panelUtama.add(btnKelolaPeminjaman);
        panelUtama.add(btnLogout);
           
    }//GEN-LAST:event_formKelolaBukuActionPerformed

    private void btnKelolaBukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKelolaBukuActionPerformed
        // TODO add your handling code here:
        
        // Menghapus komponen lain di panel utama
        panelUtama.removeAll();
        panelUtama.repaint();
        
        // Instance class form kelola buku
        formKelolaBuku kelolaBuku = new formKelolaBuku();
        
        // Mengambil ukuran layar utama dan layar form kelola buku
        Dimension layarUtama = this.getSize();
        Dimension layarKelolaBuku = kelolaBuku.getSize();
        
        // Set posisi form kelola buku ke center
        kelolaBuku.setLocation((layarUtama.width - layarKelolaBuku.width)/2, (layarUtama.height - layarKelolaBuku.height)/4);
        
        // Menambahkan halaman form kelola buku di panel utama
        panelUtama.add(kelolaBuku);
        kelolaBuku.setVisible(true);
        
        panelUtama.add(lblGreet);
        panelUtama.add(btnKelolaBuku);
        panelUtama.add(btnKelolaAnggota);
        panelUtama.add(btnKelolaPeminjaman);
        panelUtama.add(btnLogout);
    }//GEN-LAST:event_btnKelolaBukuActionPerformed

    private void btnKelolaAnggotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKelolaAnggotaActionPerformed
        // Menghapus komponen lain di panel utama
        panelUtama.removeAll();
        panelUtama.repaint();
        
        // Instance class form kelola anggota
        formKelolaAnggota kelolaAnggota = new formKelolaAnggota();
        
        // Mengambil ukuran layar utama dan layar form kelola anggota
        Dimension layarUtama = this.getSize();
        Dimension layarKelolaAnggota = kelolaAnggota.getSize();
        
        // Set posisi form kelola anggota ke center
        kelolaAnggota.setLocation((layarUtama.width - layarKelolaAnggota.width)/2, (layarUtama.height - layarKelolaAnggota.height)/4);
        
        // Menambahkan halaman form kelola anggota di panel utama
        panelUtama.add(kelolaAnggota);
        kelolaAnggota.setVisible(true);
        
        panelUtama.add(lblGreet);
        panelUtama.add(btnKelolaBuku);
        panelUtama.add(btnKelolaAnggota);
        panelUtama.add(btnKelolaPeminjaman);
        panelUtama.add(btnLogout);
    }//GEN-LAST:event_btnKelolaAnggotaActionPerformed

    private void formKelolaAnggotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_formKelolaAnggotaActionPerformed
        // TODO add your handling code here:
        // Menghapus komponen lain di panel utama
        panelUtama.removeAll();
        panelUtama.repaint();
        
        // Instance class form kelola anggota
        formKelolaAnggota kelolaAnggota = new formKelolaAnggota();
        
        // Mengambil ukuran layar utama dan layar form kelola anggota
        Dimension layarUtama = this.getSize();
        Dimension layarKelolaAnggota = kelolaAnggota.getSize();
        
        // Set posisi form kelola anggota ke center
        kelolaAnggota.setLocation((layarUtama.width - layarKelolaAnggota.width)/2, (layarUtama.height - layarKelolaAnggota.height)/4);
        
        // Menambahkan halaman form kelola anggota di panel utama
        panelUtama.add(kelolaAnggota);
        kelolaAnggota.setVisible(true);
        
        panelUtama.add(lblGreet);
        panelUtama.add(btnKelolaBuku);
        panelUtama.add(btnKelolaAnggota);
        panelUtama.add(btnKelolaPeminjaman);
        panelUtama.add(btnLogout);
    }//GEN-LAST:event_formKelolaAnggotaActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // Instance menu login
        menuLogin menuLogin = new menuLogin();
        
        // Tampilkan menu login utama
        menuLogin.setVisible(true);
        
        // Hapus tampilan form utama admin
        this.dispose();
        
        // Tampilkan pesan berhasil
        JOptionPane.showMessageDialog(null, "Anda berhasil logout");
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void formKelolaPeminjamanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_formKelolaPeminjamanActionPerformed
        
        // TODO add your handling code here:
        // Menghapus komponen lain di panel utama
        panelUtama.removeAll();
        panelUtama.repaint();
        
        // Instance class form kelola peminjaman
        formKelolaPeminjaman kelolaPeminjaman = new formKelolaPeminjaman();
        
        // Mengambil ukuran layar utama dan layar form kelola peminjaman
        Dimension layarUtama = this.getSize();
        Dimension layarKelolaPeminjaman = kelolaPeminjaman.getSize();
        
        // Set posisi form kelola peminjaman ke center
        kelolaPeminjaman.setLocation((layarUtama.width - layarKelolaPeminjaman.width)/2, (layarUtama.height - layarKelolaPeminjaman.height)/4);
        
        // Menambahkan halaman form kelola peminjaman di panel utama
        panelUtama.add(kelolaPeminjaman);
        kelolaPeminjaman.setVisible(true);
        
        panelUtama.add(lblGreet);
        panelUtama.add(btnKelolaBuku);
        panelUtama.add(btnKelolaAnggota);
        panelUtama.add(btnKelolaPeminjaman);
        panelUtama.add(btnLogout);
    }//GEN-LAST:event_formKelolaPeminjamanActionPerformed

    private void btnKelolaPeminjamanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKelolaPeminjamanActionPerformed
        // TODO add your handling code here:
        // Menghapus komponen lain di panel utama
        panelUtama.removeAll();
        panelUtama.repaint();
        
        // Instance class form kelola peminjaman
        formKelolaPeminjaman kelolaPeminjaman = new formKelolaPeminjaman();
        
        // Mengambil ukuran layar utama dan layar form kelola peminjaman
        Dimension layarUtama = this.getSize();
        Dimension layarKelolaPeminjaman = kelolaPeminjaman.getSize();
        
        // Set posisi form kelola peminjaman ke center
        kelolaPeminjaman.setLocation((layarUtama.width - layarKelolaPeminjaman.width)/2, (layarUtama.height - layarKelolaPeminjaman.height)/4);
        
        // Menambahkan halaman form kelola peminjaman di panel utama
        panelUtama.add(kelolaPeminjaman);
        kelolaPeminjaman.setVisible(true);
        
        panelUtama.add(lblGreet);
        panelUtama.add(btnKelolaBuku);
        panelUtama.add(btnKelolaAnggota);
        panelUtama.add(btnKelolaPeminjaman);
        panelUtama.add(btnLogout);
    }//GEN-LAST:event_btnKelolaPeminjamanActionPerformed

    private void menuTentangKitaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuTentangKitaMouseClicked
        // TODO add your handling code here:
        // Menghapus komponen lain di panel utama
        panelUtama.removeAll();
        panelUtama.repaint();
        
        // Instance class form kelola peminjaman
        formTentangKami tentangKita = new formTentangKami();
        
        // Mengambil ukuran layar utama dan layar form kelola peminjaman
        Dimension layarUtama = this.getSize();
        Dimension layarTentangKita = tentangKita.getSize();
        
        // Set posisi form kelola peminjaman ke center
        tentangKita.setLocation((layarUtama.width - layarTentangKita.width)/2, (layarUtama.height - layarTentangKita.height)/4);
        
        // Menambahkan halaman form kelola peminjaman di panel utama
        panelUtama.add(tentangKita);
        tentangKita.setVisible(true);
        
        panelUtama.add(lblGreet);
        panelUtama.add(btnKelolaBuku);
        panelUtama.add(btnKelolaAnggota);
        panelUtama.add(btnKelolaPeminjaman);
        panelUtama.add(btnLogout);
    }//GEN-LAST:event_menuTentangKitaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(formUtamaAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(formUtamaAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(formUtamaAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formUtamaAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new formUtamaAdmin().setVisible(true);
                
               
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnKelolaAnggota;
    private javax.swing.JButton btnKelolaBuku;
    private javax.swing.JButton btnKelolaPeminjaman;
    private javax.swing.JButton btnLogout;
    private javax.swing.JMenuItem formKelolaAnggota;
    private javax.swing.JMenuItem formKelolaBuku;
    private javax.swing.JMenuItem formKelolaPeminjaman;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JLabel lblGreet;
    private javax.swing.JMenu menuAkun;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu menuData;
    private javax.swing.JMenuItem menuLogout;
    private javax.swing.JMenu menuTentangKita;
    private javax.swing.JDesktopPane panelUtama;
    // End of variables declaration//GEN-END:variables
}
