package form;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import perpustakaan.Koneksi;
import perpustakaan.menuLogin;

/**
 *
 * @author oyeaaa
 */
public class formDaftarAnggota extends javax.swing.JFrame {

    /**
     * Creates new form formDaftarAnggota
     */
    public formDaftarAnggota() {
        initComponents();
    }
    
    // Method untuk cek username apakah sudah dipakai atau belum
    private boolean cek_username(String x) {
        // Koneksi ke database
        Connection kon = Koneksi.koneksiDB();
        
        // Set username false
        boolean username = false;
        
        try {
            
            // Mempersiapkan statement
            Statement stmt = kon.createStatement();
            
            // Query sql
            String sql = "SELECT username FROM anggota WHERE username = '"+x+"'";
            
            // Eksekusi Query ke database
            ResultSet rs = stmt.executeQuery(sql);
            
            // Jika query / username ditemukan
            // Set username ke true ( username sudah ada )
            if(rs.next()) {
                username = true;
            }
        }catch(Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
        
        // Kembalikan nilai username
        return username;
    }
    
    public void daftar_anggota() {
        
        // Koneksi ke database
        Connection kon = Koneksi.koneksiDB();
        
        try {
            
            // Mempersiapkan Statement
            Statement stmt = kon.createStatement();
            
            // Query database / sql
            String sql = "INSERT INTO anggota (id_anggota, nama_anggota, no_tlp, alamat, username, password, status)"
                    + " VALUES (default,"
                    + "'"+txtNama.getText()
                    +"','"+txtNoTlp.getText()
                    +"','"+txtAlamat.getText()
                    +"','"+txtUsername.getText()
                    +"','"+txtPassword.getText()
                    +"', 'AKTIF');";
            
            // Eksekusi query ke database
            int baris = stmt.executeUpdate(sql);
            
            // Jika baris / data bertambah
            // Lanjutkan ke menu login dan tampilkan pesan berhasil
            if(baris > 0) {
                JOptionPane.showMessageDialog(null, "Pendaftaran Berhasil! Silahkan Login!");
                menuLogin menu = new menuLogin();
                menu.show();
                this.dispose();
            } else {
                JOptionPane.showMessageDialog(null, "Pendaftaran Gagal!");
            }
        } catch(SQLException e) {
            JOptionPane.showMessageDialog(null, "Error: "+e);
        }
    }
    
    // Method untuk cek validasi field harus semua diisi
    // Method untuk cek username apakah sudah digunakan atau belum
    private boolean cek_validasi() {
        boolean validasi = false;
        
        if(txtNama.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Nama Wajib Diisi!");
            txtNama.requestFocus();
        } else if(txtNoTlp.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "No Telepon Wajib Diisi!");
            txtNoTlp.requestFocus();
        } else if(txtAlamat.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Alamat Wajib Diisi!");
            txtAlamat.requestFocus();
        } else if(txtUsername.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Username Wajib Diisi!");
            txtUsername.requestFocus();
        } else if(txtPassword.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Password Wajib Diisi!");
            txtPassword.requestFocus();
        } else if(cek_username(txtUsername.getText())) {
            JOptionPane.showMessageDialog(null, "Username sudah digunakan!");
            txtUsername.requestFocus();
        } else {
            validasi = true;
        }
           
        return validasi;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        lblNamaAnggota = new javax.swing.JLabel();
        lblNoTlp = new javax.swing.JLabel();
        lblAlamat = new javax.swing.JLabel();
        lblUsername = new javax.swing.JLabel();
        lblPassword = new javax.swing.JLabel();
        txtNama = new javax.swing.JTextField();
        txtNoTlp = new javax.swing.JTextField();
        txtAlamat = new javax.swing.JTextField();
        txtUsername = new javax.swing.JTextField();
        txtPassword = new javax.swing.JPasswordField();
        btnDaftar = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        btnKembali = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("DAFTAR ANGGOTA");

        lblTitle.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        lblTitle.setText("DAFTAR ANGGOTA");

        lblNamaAnggota.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblNamaAnggota.setText("Nama Anggota");

        lblNoTlp.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblNoTlp.setText("No Telepon");

        lblAlamat.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblAlamat.setText("Alamat");

        lblUsername.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblUsername.setText("Username");

        lblPassword.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblPassword.setText("Password");

        btnDaftar.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnDaftar.setText("DAFTAR");
        btnDaftar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDaftarActionPerformed(evt);
            }
        });

        btnReset.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnReset.setText("RESET");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        btnKembali.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/back.png"))); // NOI18N
        btnKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKembaliActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnKembali, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addComponent(btnDaftar, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(107, 107, 107))
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(lblPassword)
                        .addComponent(lblUsername)
                        .addComponent(lblAlamat)
                        .addComponent(txtNama)
                        .addComponent(lblNamaAnggota)
                        .addComponent(lblNoTlp)
                        .addComponent(txtNoTlp)
                        .addComponent(txtAlamat)
                        .addComponent(txtUsername)
                        .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblTitle))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnKembali, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTitle)
                .addGap(18, 18, 18)
                .addComponent(lblNamaAnggota)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblNoTlp)
                .addGap(3, 3, 3)
                .addComponent(txtNoTlp, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblAlamat)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtAlamat, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblUsername)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblPassword)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDaftar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDaftarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDaftarActionPerformed
        // Cek validasi apakah semua field sudah diisi
        // Cek username apakah sudah digunakan
        // Username harus unik
        
        if(cek_validasi()) {
            daftar_anggota();
        }
    }//GEN-LAST:event_btnDaftarActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        // Reset semua field
   
        txtNama.setText("");
        txtNoTlp.setText("");
        txtAlamat.setText("");
        txtUsername.setText("");
        txtPassword.setText("");
        txtNama.requestFocus();
    }//GEN-LAST:event_btnResetActionPerformed

    private void btnKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKembaliActionPerformed
        // Jika tombol kembali ditekan, maka kembali ke halaman utama
        menuLogin menuLogin = new menuLogin();
        
        menuLogin.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnKembaliActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(formDaftarAnggota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(formDaftarAnggota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(formDaftarAnggota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formDaftarAnggota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new formDaftarAnggota().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDaftar;
    private javax.swing.JButton btnKembali;
    private javax.swing.JButton btnReset;
    private javax.swing.JLabel lblAlamat;
    private javax.swing.JLabel lblNamaAnggota;
    private javax.swing.JLabel lblNoTlp;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JTextField txtAlamat;
    private javax.swing.JTextField txtNama;
    private javax.swing.JTextField txtNoTlp;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
