package form;

/**
 *
 * @author oyeaaa
 */
public class formTentangKami extends javax.swing.JInternalFrame {

    /**
     * Creates new form formTentangKita
     */
    public formTentangKami() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        fotoRifqi = new javax.swing.JLabel();
        lblRifqiPratama = new javax.swing.JLabel();
        lblNimRifqi = new javax.swing.JLabel();
        fotoAdit = new javax.swing.JLabel();
        lblAdit = new javax.swing.JLabel();
        lblNimAdit = new javax.swing.JLabel();
        fotoLuthfi = new javax.swing.JLabel();
        lblLuthfi = new javax.swing.JLabel();
        lblNimLuthfi = new javax.swing.JLabel();
        fotoNovel = new javax.swing.JLabel();
        lblNovel = new javax.swing.JLabel();
        lblNimNovel = new javax.swing.JLabel();
        fotoRafi = new javax.swing.JLabel();
        lblRafi = new javax.swing.JLabel();
        lblNimRafi = new javax.swing.JLabel();
        btnKembali = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(1366, 632));

        lblTitle.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("KELOMPOK PERPUSTAKAAN - IF 8");
        lblTitle.setPreferredSize(new java.awt.Dimension(1366, 43));

        fotoRifqi.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fotoRifqi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/rifqi.png"))); // NOI18N

        lblRifqiPratama.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblRifqiPratama.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRifqiPratama.setText("RIFQI PRATAMA J");

        lblNimRifqi.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblNimRifqi.setText("10118322");

        fotoAdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/adit.png"))); // NOI18N

        lblAdit.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblAdit.setText("ADITTYA KAMAL");

        lblNimAdit.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblNimAdit.setText("10118337");

        fotoLuthfi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/luthfi.png"))); // NOI18N

        lblLuthfi.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblLuthfi.setText("LUTHFI RIFQI Z");

        lblNimLuthfi.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblNimLuthfi.setText("10118312");

        fotoNovel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/novel.png"))); // NOI18N

        lblNovel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblNovel.setText("MUHAMMAD NOVEL Z");

        lblNimNovel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblNimNovel.setText("10118348");

        fotoRafi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/rafi.png"))); // NOI18N

        lblRafi.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblRafi.setText("M. RAFI AVISINA");

        lblNimRafi.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblNimRafi.setText("10118328");

        btnKembali.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/back.png"))); // NOI18N
        btnKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKembaliActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/ijal.png"))); // NOI18N
        jLabel1.setText("jLabel1");

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setText("M. RIJAL SULAEMAN");

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel3.setText("10118341");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(49, 49, 49)
                            .addComponent(fotoRifqi, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(lblRifqiPratama, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(lblNimRifqi)
                        .addGap(62, 62, 62)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(fotoAdit, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblAdit))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(75, 75, 75)
                                .addComponent(fotoLuthfi, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(87, 87, 87)
                                .addComponent(fotoNovel, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(89, 89, 89)
                                .addComponent(lblLuthfi)
                                .addGap(74, 74, 74)
                                .addComponent(lblNovel)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(77, 77, 77)
                                .addComponent(fotoRafi, javax.swing.GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(135, 135, 135))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(90, 90, 90)
                                .addComponent(lblRafi)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addComponent(lblNimAdit)
                        .addGap(136, 136, 136)
                        .addComponent(lblNimLuthfi)
                        .addGap(131, 131, 131)
                        .addComponent(lblNimNovel)
                        .addGap(159, 159, 159)
                        .addComponent(lblNimRafi)
                        .addGap(100, 100, 100)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addComponent(jLabel3)))
                        .addContainerGap())))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnKembali, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(btnKembali, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(92, 92, 92)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(fotoRifqi, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblRifqiPratama)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblNimRifqi))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(fotoLuthfi, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fotoAdit, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fotoNovel, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fotoRafi, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblAdit)
                            .addComponent(lblLuthfi)
                            .addComponent(lblNovel)
                            .addComponent(lblRafi)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNimAdit)
                            .addComponent(lblNimLuthfi)
                            .addComponent(lblNimNovel)
                            .addComponent(lblNimRafi)
                            .addComponent(jLabel3))))
                .addContainerGap(200, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKembaliActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnKembaliActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnKembali;
    private javax.swing.JLabel fotoAdit;
    private javax.swing.JLabel fotoLuthfi;
    private javax.swing.JLabel fotoNovel;
    private javax.swing.JLabel fotoRafi;
    private javax.swing.JLabel fotoRifqi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblAdit;
    private javax.swing.JLabel lblLuthfi;
    private javax.swing.JLabel lblNimAdit;
    private javax.swing.JLabel lblNimLuthfi;
    private javax.swing.JLabel lblNimNovel;
    private javax.swing.JLabel lblNimRafi;
    private javax.swing.JLabel lblNimRifqi;
    private javax.swing.JLabel lblNovel;
    private javax.swing.JLabel lblRafi;
    private javax.swing.JLabel lblRifqiPratama;
    private javax.swing.JLabel lblTitle;
    // End of variables declaration//GEN-END:variables
}
