package perpustakaan;

import form.formDaftarAnggota;
import form.formLoginAdmin;
import form.formLoginAnggota;
import java.awt.Component;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;

/**
 *
 * @author oyeaaa
 */
public class menuLogin extends javax.swing.JFrame {

    SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
    Date date = new Date();

    // Mendapatkan tanggal sekarang
    String tanggalSekarang = dateFormat.format(date);
    
    public static class customUI extends Component {
        
        // Konstruktor
        public customUI() {
            
        }
    }
    /**
     * Creates new form MenuLogin
     */
    public menuLogin() {
        initComponents();
        
        // Jika status peminjaman masih dipinjam pada tanggal hari ini
        if(cek_status_peminjaman().equals("DIPINJAM")) {
            kembalikan_otomatis();
        }
    }
   
    // Method kembalikan buku otomatis
    private void kembalikan_otomatis() {

        // Koneksi ke database
        Connection kon = Koneksi.koneksiDB();
        
        try {
            
            // Mempersiapkan statement
            Statement stmt = kon.createStatement();
            
            // Query sql
            String sql = "UPDATE detail_peminjaman SET status = 'DIKEMBALIKAN'"
                    + "WHERE tanggal_kembali = '"+tanggalSekarang+"'";
            
            // Query sql2
            String sql2 = "UPDATE buku SET stok = stok + 1 "
                    + "WHERE id_buku IN ( SELECT id_buku FROM detail_peminjaman "
                    + "WHERE tanggal_kembali = '"+tanggalSekarang+"')";
            
            // Eksekusi query
            int baris = stmt.executeUpdate(sql);
            int baris2 = stmt.executeUpdate(sql2);
             
        } catch(Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }
    
    // Method untuk mengecek status peminjaman buku
    private String cek_status_peminjaman() {
        
        // Koneksi ke database
        Connection kon = Koneksi.koneksiDB();
        
        String status = "";
        try {
            
            // Mempersiapkan statement
            Statement stmt = kon.createStatement();
            
            // Query sql
            String sql = "SELECT status FROM detail_peminjaman WHERE tanggal_kembali = '"+tanggalSekarang+"'";
            
            // Eksekusi query sql
            ResultSet rs = stmt.executeQuery(sql);
            
            // Mendapatkan data dari hasil query
            while(rs.next()) {
                status = rs.getString(1);
            }
        } catch(Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
        
        return status;
    }
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        btnLoginAdmin = new javax.swing.JButton();
        btnLoginAnggota = new javax.swing.JButton();
        btnDaftar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("APLIKASI PERPUSTAKAAN");

        lblTitle.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("APLIKASI PERPUSTAKAAN");

        btnLoginAdmin.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnLoginAdmin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/admin.png"))); // NOI18N
        btnLoginAdmin.setText("LOGIN ADMIN");
        btnLoginAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginAdminActionPerformed(evt);
            }
        });

        btnLoginAnggota.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnLoginAnggota.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/anggota.png"))); // NOI18N
        btnLoginAnggota.setText("LOGIN ANGGOTA");
        btnLoginAnggota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginAnggotaActionPerformed(evt);
            }
        });

        btnDaftar.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnDaftar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/daftar-anggota.png"))); // NOI18N
        btnDaftar.setText("DAFTAR ANGGOTA");
        btnDaftar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDaftarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnDaftar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnLoginAnggota, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnLoginAdmin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(lblTitle)
                .addGap(18, 18, 18)
                .addComponent(btnLoginAdmin)
                .addGap(18, 18, 18)
                .addComponent(btnLoginAnggota)
                .addGap(18, 18, 18)
                .addComponent(btnDaftar, javax.swing.GroupLayout.PREFERRED_SIZE, 87, Short.MAX_VALUE)
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginAdminActionPerformed
        // Jika menu login admin dipilih / diklik lanjutkan ke menu login admin
        formLoginAdmin loginAdmin = new formLoginAdmin();
        loginAdmin.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnLoginAdminActionPerformed

    private void btnLoginAnggotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginAnggotaActionPerformed
        // Jika menu login anggota dipilih / diklik lanjutkan ke menu login anggota
        formLoginAnggota loginAnggota = new formLoginAnggota();
        loginAnggota.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnLoginAnggotaActionPerformed

    private void btnDaftarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDaftarActionPerformed
        // Jika menu daftar anggota dipilih / diklik lanjutkan ke menu daftar anggota
        formDaftarAnggota daftarAnggota = new formDaftarAnggota();
        daftarAnggota.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnDaftarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            UIManager.setLookAndFeel("com.jtattoo.plaf.fast.FastLookAndFeel");
            SwingUtilities.updateComponentTreeUI(new customUI());
        }catch(Exception e) {
            JOptionPane.showMessageDialog(null, "Error: " + e);
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menuLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDaftar;
    private javax.swing.JButton btnLoginAdmin;
    private javax.swing.JButton btnLoginAnggota;
    private javax.swing.JLabel lblTitle;
    // End of variables declaration//GEN-END:variables
}
